CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218200513_MigratePortfolioIdToShortString') THEN
    CREATE TABLE "Users" (
        "Id" uuid NOT NULL,
        "CognitoSub" character varying(100) NOT NULL,
        "Email" character varying(255) NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218200513_MigratePortfolioIdToShortString') THEN
    CREATE TABLE "Portfolios" (
        "Id" character varying(6) NOT NULL,
        "SequentialId" bigint GENERATED BY DEFAULT AS IDENTITY,
        "PersonId" character varying(120) NOT NULL,
        "DisplayName" character varying(200) NOT NULL,
        "Subdomain" character varying(120),
        "IsActive" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "OwnerId" uuid NOT NULL,
        CONSTRAINT "PK_Portfolios" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Portfolios_Users_OwnerId" FOREIGN KEY ("OwnerId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218200513_MigratePortfolioIdToShortString') THEN
    CREATE TABLE "PortfolioAssets" (
        "Id" uuid NOT NULL,
        "PortfolioId" character varying(6) NOT NULL,
        "AssetKey" character varying(255) NOT NULL,
        "S3Url" character varying(500) NOT NULL,
        "CloudFrontUrl" character varying(500) NOT NULL,
        "FileType" character varying(50) NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_PortfolioAssets" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_PortfolioAssets_Portfolios_PortfolioId" FOREIGN KEY ("PortfolioId") REFERENCES "Portfolios" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218200513_MigratePortfolioIdToShortString') THEN
    CREATE TABLE "PortfolioLocales" (
        "Id" uuid NOT NULL,
        "PortfolioId" character varying(6) NOT NULL,
        "Language" character varying(10) NOT NULL,
        "ContentJson" jsonb NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_PortfolioLocales" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_PortfolioLocales_Portfolios_PortfolioId" FOREIGN KEY ("PortfolioId") REFERENCES "Portfolios" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218200513_MigratePortfolioIdToShortString') THEN
    CREATE UNIQUE INDEX "IX_PortfolioAssets_PortfolioId_AssetKey" ON "PortfolioAssets" ("PortfolioId", "AssetKey");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218200513_MigratePortfolioIdToShortString') THEN
    CREATE UNIQUE INDEX "IX_PortfolioLocales_PortfolioId_Language" ON "PortfolioLocales" ("PortfolioId", "Language");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218200513_MigratePortfolioIdToShortString') THEN
    CREATE INDEX "IX_Portfolios_OwnerId" ON "Portfolios" ("OwnerId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218200513_MigratePortfolioIdToShortString') THEN
    CREATE UNIQUE INDEX "IX_Portfolios_PersonId" ON "Portfolios" ("PersonId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218200513_MigratePortfolioIdToShortString') THEN
    CREATE UNIQUE INDEX "IX_Portfolios_SequentialId" ON "Portfolios" ("SequentialId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218200513_MigratePortfolioIdToShortString') THEN
    CREATE UNIQUE INDEX "IX_Portfolios_Subdomain" ON "Portfolios" ("Subdomain");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218200513_MigratePortfolioIdToShortString') THEN
    CREATE UNIQUE INDEX "IX_Users_CognitoSub" ON "Users" ("CognitoSub");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218200513_MigratePortfolioIdToShortString') THEN
    CREATE INDEX "IX_Users_Email" ON "Users" ("Email");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218200513_MigratePortfolioIdToShortString') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251218200513_MigratePortfolioIdToShortString', '8.0.10');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260112165220_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260112165220_InitialCreate', '8.0.10');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260112222327_UpdateUserSubjectAndProvider') THEN
    ALTER TABLE "Users" RENAME COLUMN "CognitoSub" TO "Subject";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260112222327_UpdateUserSubjectAndProvider') THEN
    ALTER INDEX "IX_Users_CognitoSub" RENAME TO "IX_Users_Subject";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260112222327_UpdateUserSubjectAndProvider') THEN
    ALTER TABLE "Users" ADD "Issuer" character varying(255) NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260112222327_UpdateUserSubjectAndProvider') THEN
    ALTER TABLE "Users" ADD "LastLoginAt" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260112222327_UpdateUserSubjectAndProvider') THEN
    ALTER TABLE "Users" ADD "Provider" character varying(100) NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260112222327_UpdateUserSubjectAndProvider') THEN
    CREATE UNIQUE INDEX "IX_Users_Subject_Issuer" ON "Users" ("Subject", "Issuer");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260112222327_UpdateUserSubjectAndProvider') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260112222327_UpdateUserSubjectAndProvider', '8.0.10');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260116213604_ChangeVersionIdToInteger') THEN
    CREATE TABLE "PortfolioVersions" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "PortfolioId" character varying(6) NOT NULL,
        "VersionNumber" integer NOT NULL,
        "Status" integer NOT NULL,
        "Label" character varying(200),
        "ChangeDescription" character varying(2000),
        "LocaleSnapshot" jsonb NOT NULL,
        "CreatedBy" uuid NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "PublishedAt" timestamp with time zone,
        "PublishedBy" uuid,
        "IsCurrentPublished" boolean NOT NULL,
        CONSTRAINT "PK_PortfolioVersions" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_PortfolioVersions_Portfolios_PortfolioId" FOREIGN KEY ("PortfolioId") REFERENCES "Portfolios" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_PortfolioVersions_Users_CreatedBy" FOREIGN KEY ("CreatedBy") REFERENCES "Users" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260116213604_ChangeVersionIdToInteger') THEN
    CREATE INDEX "IX_PortfolioVersions_CreatedBy" ON "PortfolioVersions" ("CreatedBy");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260116213604_ChangeVersionIdToInteger') THEN
    CREATE INDEX "IX_PortfolioVersions_PortfolioId_IsCurrentPublished" ON "PortfolioVersions" ("PortfolioId", "IsCurrentPublished");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260116213604_ChangeVersionIdToInteger') THEN
    CREATE INDEX "IX_PortfolioVersions_PortfolioId_Status" ON "PortfolioVersions" ("PortfolioId", "Status");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260116213604_ChangeVersionIdToInteger') THEN
    CREATE UNIQUE INDEX "IX_PortfolioVersions_PortfolioId_VersionNumber" ON "PortfolioVersions" ("PortfolioId", "VersionNumber");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260116213604_ChangeVersionIdToInteger') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260116213604_ChangeVersionIdToInteger', '8.0.10');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260116214459_AddUniqueConstraintToVersionNumber') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260116214459_AddUniqueConstraintToVersionNumber', '8.0.10');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260116214643_AddVersionNumberUniqueIndex') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260116214643_AddVersionNumberUniqueIndex', '8.0.10');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260119040959_ChangeLocaleSnapshotToJson') THEN
    ALTER TABLE "PortfolioVersions" ALTER COLUMN "LocaleSnapshot" TYPE json USING "LocaleSnapshot"::json;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260119040959_ChangeLocaleSnapshotToJson') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260119040959_ChangeLocaleSnapshotToJson', '8.0.10');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260119154011_AddVersionSoftDelete') THEN
    ALTER TABLE "PortfolioVersions" ADD COLUMN "IsDeleted" boolean NOT NULL DEFAULT false;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260119154011_AddVersionSoftDelete') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260119154011_AddVersionSoftDelete', '8.0.10');
    END IF;
END $EF$;
COMMIT;

