START TRANSACTION;

CREATE TABLE "PortfolioVersions" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PortfolioId" character varying(6) NOT NULL,
    "VersionNumber" integer NOT NULL,
    "Status" integer NOT NULL,
    "Label" character varying(200),
    "ChangeDescription" character varying(2000),
    "LocaleSnapshot" jsonb NOT NULL,
    "CreatedBy" uuid NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "PublishedAt" timestamp with time zone,
    "PublishedBy" uuid,
    "IsCurrentPublished" boolean NOT NULL,
    CONSTRAINT "PK_PortfolioVersions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PortfolioVersions_Portfolios_PortfolioId" FOREIGN KEY ("PortfolioId") REFERENCES "Portfolios" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_PortfolioVersions_Users_CreatedBy" FOREIGN KEY ("CreatedBy") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);

CREATE INDEX "IX_PortfolioVersions_CreatedBy" ON "PortfolioVersions" ("CreatedBy");

CREATE INDEX "IX_PortfolioVersions_PortfolioId_IsCurrentPublished" ON "PortfolioVersions" ("PortfolioId", "IsCurrentPublished");

CREATE INDEX "IX_PortfolioVersions_PortfolioId_Status" ON "PortfolioVersions" ("PortfolioId", "Status");

CREATE UNIQUE INDEX "IX_PortfolioVersions_PortfolioId_VersionNumber" ON "PortfolioVersions" ("PortfolioId", "VersionNumber");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260116213604_ChangeVersionIdToInteger', '8.0.10');

COMMIT;

START TRANSACTION;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260116214459_AddUniqueConstraintToVersionNumber', '8.0.10');

COMMIT;

START TRANSACTION;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260116214643_AddVersionNumberUniqueIndex', '8.0.10');

COMMIT;

START TRANSACTION;

ALTER TABLE "PortfolioLocales" ALTER COLUMN "ContentJson" TYPE json;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260118040835_ChangeContentJsonToTextJson', '8.0.10');

COMMIT;

START TRANSACTION;

ALTER TABLE "PortfolioVersions" ALTER COLUMN "LocaleSnapshot" TYPE json;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260119040959_ChangeLocaleSnapshotToJson', '8.0.10');

COMMIT;

